# AU template: https://github.com/majkinetor/au-packages-template

version: '{build}'

environment:
  # Set au version to use or omit to use the latest.
  au_version:

install:
- ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
- ps: $PSVersionTable
- git --version
- choco --version
- ps: |
    git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
    . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version

- ps: |
    "Build info"
    '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
    '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
    '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')

# Uncomment the below line if you are using any of the functions from chocolatey-core.extension - https://chocolatey.org/packages/chocolatey-core.extension. Ensure you also have it listed in your package's dependencies
# - cinst chocolatey-core.extension
    
build_script:
- ps: |
    $au_NoCheckChocoVersion = $true
    ./update.ps1
    choco pack

test_script:
  - ps: choco install snowflakeodbcdriver --source="'.;https://chocolatey.org/api/v2'" -dvy
  - ps: choco uninstall snowflakeodbcdriver -dvy

artifacts:
  - path: '**\*.nupkg'